### ISSUE TITLE
Thanks for the inspiration!

### ISSUE THREAD

**Issue by bbkane** [TwiN/go-color#4]
### Describe the feature request

The simplicity of this library inspired me to write my own simple [color library](https://github.com/bbkane/gocolor). Thank you!

Some things you might be interested in grabbing from `gocolor`:

- [codegen to add more colors](https://github.com/bbkane/gocolor/blob/master/scripts/color_gen.py) from the ANSI colors supported on Windows (and they copied from Unix so they work there too)
- [Color.Func](https://pkg.go.dev/github.com/bbkane/gocolor#Color.Func) to let users easily create their own color funcs

**Comment by TwiN** [comment]
Awesome work! I'm always glad to see new libraries pop up, even if there are already existing options, as it helps prevent a monopoly from forming around a requirement.

Best of luck with your color library!
